POST http://localhost:8001/books
Content-Type: application/json

{"id": 5,"name": "tom"}

###

DELETE http://localhost:8001/books/1
Accept: application/json


###

GET http://localhost:8001/books/
Accept: application/json

###

PUT http://localhost:8001/books/4
Content-Type: application/json

{"name": "abc"}

###